apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:4df4bae158384863ab7ff6e2b57b5d270fded804
        ports:
        - containerPort: 80
