apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:d48c56732354e6c7a6a438bb0553e1865f1b7022
        ports:
        - containerPort: 80
