apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:d48c56732354e6c7a6a438bb0553e1865f1b7022
        ports:
        - containerPort: 80
