apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:54860de2b4248c2469c3e4141c1789cc5ba0b959
        ports:
        - containerPort: 80
