apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 683707058733.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:c8e7a7295b956615cfa2ca7a6d0642997e02a223
        ports:
        - containerPort: 80
