apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:d48c56732354e6c7a6a438bb0553e1865f1b7022
          ports:
            - containerPort: 5000
