apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 683707058733.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:ac37d3f703262c6f5afc4f2734baba5dcde7c921
          ports:
            - containerPort: 5000
