apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:4df4bae158384863ab7ff6e2b57b5d270fded804
        ports:
        - containerPort: 80
