apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:4c139d595ee028be721be4c50d454c01baab114b
        ports:
        - containerPort: 80
