apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:3ac90f8d6ff9fcf4c559584fe5bd98b24a77e922
        ports:
        - containerPort: 80
