apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-main:4c139d595ee028be721be4c50d454c01baab114b
        ports:
        - containerPort: 80

