apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-main:d48c56732354e6c7a6a438bb0553e1865f1b7022
        ports:
        - containerPort: 80

