apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:6a940b2e92995a03a283d01be248cda9708f1203
        ports:
        - containerPort: 80
