apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:51da088f3d7559ffaac4d74b593bf547442a10a1
        ports:
        - containerPort: 80
