apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:d48c56732354e6c7a6a438bb0553e1865f1b7022
        ports:
        - containerPort: 80
