apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:e1e01499d9f79652a038c27c7f54674697b56d99
        ports:
        - containerPort: 80
