apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:54860de2b4248c2469c3e4141c1789cc5ba0b959
        ports:
        - containerPort: 80
