apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 683707058733.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:c8e7a7295b956615cfa2ca7a6d0642997e02a223
        ports:
        - containerPort: 80
