apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 683707058733.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:ac37d3f703262c6f5afc4f2734baba5dcde7c921
        ports:
        - containerPort: 80
