apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:3ac90f8d6ff9fcf4c559584fe5bd98b24a77e922
        ports:
        - containerPort: 80
