apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 982630149008.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:e1e01499d9f79652a038c27c7f54674697b56d99
        ports:
        - containerPort: 80
